# Generated by Django 4.0.3 on 2022-03-13 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rubex', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='pro_cat',
            field=models.CharField(choices=[('F001', 'Sofas'), ('F002', 'Chairs'), ('F003', 'Lamp'), ('F004', 'Shelves'), ('F005', 'Baskets'), ('F006', 'Tables')], default='None', max_length=50),
        ),
    ]
